sudo: false
language: ruby
rvm: 2.5.1
script: bundle exec rake test
before_script:
  - psql -c 'create database distribute_reads_test_primary;' -U postgres
  - psql -c 'create database distribute_reads_test_replica;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/makara3.gemfile
